let seatsAvailable = 7;
let groceriesAtCheckout = 62.93;
let middleInitial = 'A';
let isHotOutside = true;
let isColdOutside = false;
let firstName = 'Barbara';
let address = '123 Baker St';
console.log(seatsAvailable);
console.log(groceriesAtCheckout);
console.log(middleInitial);
console.log(isColdOutside);
console.log(isHotOutside);
console.log(firstName);
console.log(address);
console.log(seatsAvailable - 2);
console.log(groceriesAtCheckout + 2.15);
console.log(middleInitial = 'B');
isHotOutside = !isHotOutside;
console.log(isHotOutside);
let fullName = firstName + ' ' +  middleInitial + ' Wenzl';
console.log(fullName);
console.log('Hello, my name is ' + firstName + ' and I live at ' + address + '.');